# Generated by Django 3.2.13 on 2022-09-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'todo_item', 'verbose_name_plural': 'todo_items'},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
